# Generated by Django 5.2 on 2025-05-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_alter_orderproduct_order_delete_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
