# Generated by Django 5.1.7 on 2025-04-09 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_updated_at_alter_products_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 12, 2, 3, 37952)),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
