# Generated by Django 5.2 on 2025-04-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_orderitems_orderproduct_orders_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
