# Generated by Django 5.2 on 2025-04-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_category_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profiles',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
