# Generated by Django 5.2 on 2025-05-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_alter_orderproduct_order_delete_orders'),
        ('products', '0011_remove_orders_products_remove_orders_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
